### ISSUE TITLE
Use GitHub Artifact for tdlib build

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-teaching/TelegramClient#324]
Do not download from some random DropBox, but keep the artifact in this repository and possibly automatically put them in persistent storage somewhere.

**Comment by cstes** [comment]
I'm unsure what is meant with "artifact" in the descripton of this issue.   However it seems the TelegramClient is trying to download libtdjson.so.1.6.0 from a Google drive location if it is not found in the current directory.    If this is indeed what this issue is about , the TDLib library could be installed by external means such as by operating system specific commands to install the shared library from a repository of the operating system ....    As an example, it can be done on some systems with:

pkg install telegramdb

and then

cp /usr/lib/amd64/libtdjson.so.1.6.0  .

to copy to the current directory.

**Comment by antonykamp** [comment]
see #526
