### ISSUE TITLE
CI fails more often since emojis

### ISSUE THREAD

**Issue by phkeese** [hpi-swa-teaching/TelegramClient#437]
The CI has more failures since we introduced emojis. Might be related to the downloading and unpacking of the zip file.

**Comment by rsommerfeld** [comment]
See here: https://github.com/hpi-swa-teaching/TelegramClient/actions/runs/1044889645, those pipelines happen occasionally where the pipeline only times out because of github action time limit and nothing is actually happening in the Squeak Code.

Possible causes might be a deadlock in the setup or login code of the CoreResources in Combination with some rare Timeout message from tdlib. However, other more obscure reasons are also thinkable.
