### ISSUE TITLE
Spike: animated stickers

### ISSUE THREAD

**Issue by ShAlexHo08HPI** [hpi-swa-teaching/TelegramClient#561]
Spike: As a user, i want to see animated stickers -> 8SP

**Comment by ShAlexHo** [comment]
result: 34 SP, because the animated sticker has a own telegram-specific file-type with vector-graphics
new ticket: #553

**Comment by ShAlexHo** [comment]
solution/proposal: #564

**Comment by TebbeUbben** [comment]
Animated stickers can be of two formats: WebM and TGS (a variant of Lottie). Both of which aren't supported by Squeak and aren't trivial to implement either. The easiest solution is probably to utilize external libraries like [libwebm](https://chromium.googlesource.com/webm/libwebm) and [rlottie](https://github.com/Samsung/rlottie), which is still not trivial due to the nature of displaying video.
